### ISSUE TITLE
如何循环来回播放50条数据，并且不丢失数据

### ISSUE THREAD

**Issue by sunshasha** [hugeorange/BulletJs#10]
获取数据，但是有的数据展示不出来，通过后台新增的数据，展示不出来

**Comment by hugeorange** [comment]
> 获取数据，但是有的数据展示不出来，通过后台新增的数据，展示不出来

该弹幕库的执行时机是使用者自己确定的
比如：你从后台接口获取了50条评论数据，你想依次播放并且循环，这个播放是你自己调`push`这个方法控制的，你可以1000ms播放一条，也可以10ms 播放一条，当你播放的太快的时候弹幕舞台区域会被铺满，此时为了保证弹幕不出现重叠现象，会随机丢弃一些弹幕，你可以把播放时间设长一点，

循环的问题：一个长度为50的数组，你播到最后一条，然后再从第一条重新播就可以了，这个需要使用者自己控制
