### ISSUE TITLE
只有一条弹幕的时候会抖动

### ISSUE THREAD

**Issue by ziminy** [hugeorange/BulletJs#15]
只有一条弹幕的时候会抖动，不知道是什么原因，有什么可以优化的吗？

**Comment by hugeorange** [comment]
@ziminy 能给个复现demo吗？比如 codesandbox 这样的在线示例

**Comment by ziminy** [comment]
抱歉哈，最近比较忙，后来发现生产环境没问题就没再查了，可能和我本地项目有关系~
