### ISSUE TITLE
鼠标hover暂停后会发生重叠

### ISSUE THREAD

**Issue by CLiangs** [hugeorange/BulletJs#16]
<img width="453" alt="image" src="https://user-images.githubusercontent.com/24502999/204083727-94115ab6-ea8e-4bc1-bad5-ef2f300e4523.png">

**Comment by hugeorange** [comment]
@CLiangs 这是正常的的现象，你看腾讯视频的弹幕体验也是如此
![image](https://user-images.githubusercontent.com/18440746/204521805-f0e8a084-ed27-41ad-8590-505477a8c82d.png)

当然如果你不想让两行字看着乱遭蹧的在一起，可以弹幕元素加一些样式比如背景颜色什么的或者直接禁用 hover 暂停功能 `pauseOnHover: false`

如果觉得这个弹幕库对你有用，麻烦给点个 star 😅
