### ISSUE TITLE
弹幕滚动一段时间后会出现短暂的暂停

### ISSUE THREAD

**Issue by tankle0** [hugeorange/BulletJs#19]
弹幕滚动一段时间后，暂停了一小会，又继续滚动，感觉滚动的不流畅，不仔细看发现不出来

**Comment by hugeorange** [comment]
@tankle0 能录个屏 吗，再把代码贴一下

**Comment by tankle0** [comment]
> @tankle0 能录个屏 吗，再把代码贴一下

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HappyBirthday-周年庆活动页</title>
  <style>
    #root{
      width: 80%;
      position: relative;
      left: 0;
      top: 0;
      bottom: 0;
      right: 0;
      margin: auto;
    }
    .dan{
      position: absolute;
      left: 100%;
      background: #333;
      white-space: nowrap;
      padding: 0 14px;
      border-radius: 50px;
      height: 24px;
      line-height: 24px;
      color: #fff;
      letter-spacing: 2px;
      box-shadow: 4px 4px 6px rgba(0, 0, 0, 0.2);
      cursor: default;
      top: 80px;
      animation: danmu 12s linear 0s infinite;
    }
    .screen {
      height: 100%;
    }
    @-webkit-keyframes danmu {
      from {
        -webkit-transform: translateX(0);
        transform: translateX(0);
      }
      to {
        -webkit-transform: translateX(calc(-100vw - 100%));
        transform: translateX(calc(-100vw - 100%));
      }
    }
    @keyframes danmu {
      from {
        -webkit-transform: translateX(0);
        transform: translateX(0);
      }
      to {
        -webkit-transform: translateX(calc(-100vw - 100%));
        transform: translateX(calc(-100vw - 100%));
      }
    }
    .danmu-content{
      width: 100%;
      height: 400px;
      border: 1px solid #999;
    }
    .danmu-item {
      margin: 5px;
      overflow: hidden;
      display: inline-block;
      word-break: keep-all;
      white-space: nowrap;
    }
    
  </style>
</head>
<body>
  <div id="root">
		<div class="app">
			<div class="danmu-content">
				<div class="screen"></div>
			</div>
		</div>
	</div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
  <script src="https://unpkg.com/js-bullets@0.0.1/dist/BulletJs.min.js"></script>
  
  <script>
    var danmuList = [
      "你好科比布莱恩特",
      "这个老哥的评论说的很对啊，这都能被违规隐藏？是戳痛到某些人了吗。",
      "rip....",
      "resepct",
      "😂❤️😍😒👌☺️☺️😊😭😩😩😔😏😁👍🏿😁😏😏😔💕😭😘😊❤️😍",
      "圣何塞-穆里尼奥",
      "泰伦卢，泰伦卢，泰伦卢，泰伦卢",
      "勒布朗-詹姆斯",
      "emoji",
      "湖人阵容也不是特别豪华为什么能打到西部第一？ 由高田大叔 发表在篮球·湿乎乎的话题-说的很对啊，很对啊",
      "----huhuh---hahahha---",
      "😂❤️😍😒👌☺️☺️😊😭😩😩😔😏😁👍🏿😁😏😏😔💕😭😘😊❤️😍"
    ]
    var getRandom = function(min, max) { return parseInt(Math.random() * (max - min + 1)) + min } 
    var danmuTest = {
      screen: null,
      handler: null,
      dom: {
        sendWish: document.querySelector('#sendWish'),
        dInput: document.querySelector('#inputWish'),
      },
      init() {
        this.screen = new BulletJs('.screen', {
          trackHeight: 35,
          speed: undefined,
          duration: '30s',
          speed: 120,
          pauseOnClick: true,
          pauseOnHover: true,
        });
        this.sendWish();
      },
      sendWish() {
        this.sendAction();
      },
      sendAction() {
        var that = this
        this.handler = setInterval(function() {
          var index = getRandom(0, 10);
          var str = danmuList[index];
          var dom = "<span>"+str+"</span>"
          that.screen.push(dom)
        }, 1000);
      },
      
    }

    danmuTest.init()
  </script>
</body>
</html>

**Comment by tankle0** [comment]
`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>HappyBirthday-周年庆活动页</title>
  <style>
    #root{
      width: 80%;
      position: relative;
      left: 0;
      top: 0;
      bottom: 0;
      right: 0;
      margin: auto;
    }
    .dan{
      position: absolute;
      left: 100%;
      background: #333;
      white-space: nowrap;
      padding: 0 14px;
      border-radius: 50px;
      height: 24px;
      line-height: 24px;
      color: #fff;
      letter-spacing: 2px;
      box-shadow: 4px 4px 6px rgba(0, 0, 0, 0.2);
      cursor: default;
      top: 80px;
      animation: danmu 12s linear 0s infinite;
    }
    .screen {
      height: 100%;
    }
    @-webkit-keyframes danmu {
      from {
        -webkit-transform: translateX(0);
        transform: translateX(0);
      }
      to {
        -webkit-transform: translateX(calc(-100vw - 100%));
        transform: translateX(calc(-100vw - 100%));
      }
    }
    @keyframes danmu {
      from {
        -webkit-transform: translateX(0);
        transform: translateX(0);
      }
      to {
        -webkit-transform: translateX(calc(-100vw - 100%));
        transform: translateX(calc(-100vw - 100%));
      }
    }
    .danmu-content{
      width: 100%;
      height: 400px;
      border: 1px solid #999;
    }
    .danmu-item {
      margin: 5px;
      overflow: hidden;
      display: inline-block;
      word-break: keep-all;
      white-space: nowrap;
    }
    
  </style>
</head>
<body>
  <div id="root">
		<div class="app">
			<div class="danmu-content">
				<div class="screen"></div>
			</div>
		</div>
	</div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
  <script src="https://unpkg.com/js-bullets@0.0.1/dist/BulletJs.min.js"></script>
  
  <script>
    var danmuList = [
      "你好科比布莱恩特",
      "这个老哥的评论说的很对啊，这都能被违规隐藏？是戳痛到某些人了吗。",
      "rip....",
      "resepct",
      "😂❤️😍😒👌☺️☺️😊😭😩😩😔😏😁👍🏿😁😏😏😔💕😭😘😊❤️😍",
      "圣何塞-穆里尼奥",
      "泰伦卢，泰伦卢，泰伦卢，泰伦卢",
      "勒布朗-詹姆斯",
      "emoji",
      "湖人阵容也不是特别豪华为什么能打到西部第一？ 由高田大叔 发表在篮球·湿乎乎的话题-说的很对啊，很对啊",
      "----huhuh---hahahha---",
      "😂❤️😍😒👌☺️☺️😊😭😩😩😔😏😁👍🏿😁😏😏😔💕😭😘😊❤️😍"
    ]
    var getRandom = function(min, max) { return parseInt(Math.random() * (max - min + 1)) + min } 
    var danmuTest = {
      screen: null,
      handler: null,
      dom: {
        sendWish: document.querySelector('#sendWish'),
        dInput: document.querySelector('#inputWish'),
      },
      init() {
        this.screen = new BulletJs('.screen', {
          trackHeight: 35,
          speed: undefined,
          duration: '30s',
          speed: 120,
          pauseOnClick: true,
          pauseOnHover: true,
        });
        this.sendWish();
      },
      sendWish() {
        this.sendAction();
      },
      sendAction() {
        var that = this
        this.handler = setInterval(function() {
          var index = getRandom(0, 10);
          var str = danmuList[index];
          var dom = "<span>"+str+"</span>"
          that.screen.push(dom)
        }, 1000);
      },
      
    }

    danmuTest.init()
  </script>
</body>
</html>`
