### ISSUE TITLE
请问 移动端不支持吗？一进入页面，没有弹幕效果，并且报错，

### ISSUE THREAD

**Issue by huohuo-fei** [hugeorange/BulletJs#21]
![微信图片_20231204111058](https://github.com/hugeorange/BulletJs/assets/80046818/39ea92d7-e77a-4acc-8071-3c52e0708fb6)
代码：
Uncaught TypeError: this.tempContanier.replaceChildren is not a function
/node_modules/.vite/deps/js-bullets.js?v=af2732cc:100:42 TypeError: this.tempContanier.replaceChildren is not a function
at i._getBulletItem (http://192.168.1.77:5173/node_modules/.vite/deps/js-bullets.js?v=af2732cc:100:42)
at i.push (http://192.168.1.77:5173/node_modules/.vite/deps/js-bullets.js?v=af2732cc:89:23)
at setInterval (http://192.168.1.77:5173/src/App.vue:12:12)

**Comment by hugeorange** [comment]
@huohuo-fei  初始化插件的代码发一下看看

**Comment by huohuo-fei** [comment]
@hugeorange

 <script setup>
import BulletJs from 'js-bullets';
import { onMounted } from 'vue';
onMounted(() => {
  const screen = new BulletJs('.dan-mu', {});
  setInterval(() => {
    screen.push(`
    <div class="track">
        <div class="dan" ref="dan">
          <img class="avatar" src="/src/assets/image/1.png" alt="" />
          <div class="txt">测试宽度</div>
          <img class="arrow" src="/src/assets/image/right-arr.png" alt="">
        </div>
      </div>`);
  }, 1000);
});
</script>

**Comment by huohuo-fei** [comment]
@hugeorange 
<script setup>
 import BulletJs from 'js-bullets';
 import { onMounted } from 'vue'; 
onMounted(() => {
 const screen = new BulletJs('.dan-mu', {});
  setInterval(() => {
    screen.push(`
    <div class="track">
        <div class="dan" ref="dan">
          <img class="avatar" src="/src/assets/image/1.png" alt="" />
          <div class="txt">测试宽度</div>
          <img class="arrow" src="/src/assets/image/right-arr.png" alt="">
        </div>
      </div>`);
  }, 1000);
 });
 </script>

**Comment by huohuo-fei** [comment]
@hugeorange 
![Snipaste_2023-12-04_11-23-57](https://github.com/hugeorange/BulletJs/assets/80046818/416f5779-0b79-41c7-a4f9-c8b0c5a78515)

**Comment by hugeorange** [comment]
@huohuo-fei 你有没有给 `.dan-mu` 这个 div 设置宽高，把你这整个文件都截一下图看看，这是我刚刚测试的，是好的，下面是代码，这是在线demo  https://stackblitz.com/edit/vitejs-vite-ohrvvj?file=src%2FApp.vue
```js
<script setup>
import { onMounted } from 'vue';
import BulletJs from 'js-bullets';

onMounted(() => {
  const screen = new BulletJs('#danmu-screen', {});
  setInterval(() => {
    screen.push('22222244444');
  }, 1000);
});
</script>

<template>
  <div class="wrap">
    <div id="danmu-screen"></div>
  </div>
</template>

<style scoped>
.wrap {
  border: 1px solid;
  height: 200px;
  width: 100%;
}

#danmu-screen {
  width: 100%;
  height: 100%;
  border: 1px solid red;
}
</style>

```

**Comment by hugeorange** [comment]
看你贴的第一张图是保  `dom.replaceChildren` 不是一个函数，那你的页面在电脑上能正常运行吗？我看了下 replaceChildren 的支持还可以呀  https://developer.mozilla.org/en-US/docs/Web/API/Element/replaceChildren#browser_compatibility

我两年前也在移动端用过项目也实际投产了，你的手机是什么型号的 ？

**Comment by huohuo-fei** [comment]
@hugeorange 非常感谢！！！我刚才试了下手机上其他的浏览器，发现只有手机默认的浏览器才有这个问题，然后发觉手机默认浏览器的版本低于replaceChildren要求的版本。。。
![version](https://github.com/hugeorange/BulletJs/assets/80046818/f14ddc7a-1f9a-4c0b-9d56-85e212f440e7)

**Comment by hugeorange** [comment]
@huohuo-fei  我更新了一个版本用 `appendChild` 代替 `replaceChildren` ，你再安装一下试试看 `npm i js-bullets@latest`

**Comment by huohuo-fei** [comment]
@hugeorange 好了好了，现在可以正常运行了，但是有个error提示，什么提示信息都没有，（pc端正常显示）
![newV](https://github.com/hugeorange/BulletJs/assets/80046818/e3c65e0e-5d98-4589-9fdc-d87eb296736a)

**Comment by hugeorange** [comment]
@huohuo-fei  `script error.` 是某些浏览器加载跨域脚本时会报的一个错，这个不用管的
