### ISSUE TITLE
如何首屏先把弹幕铺满呢

### ISSUE THREAD

**Issue by gt-hanyao** [hugeorange/BulletJs#22]

**Comment by hugeorange** [comment]
是需要页面一加载出来立马让屏幕内充满弹幕吗

**Comment by gt-hanyao** [comment]
是的
现在能支持吗

**Comment by hugeorange** [comment]
> 是的 现在能支持吗

直接支持，不行

但是你可以考虑下变通一下想法

比如，刚开始的时候让舞台那个div上面套盖一层loading，然后push立即几条数据，自己估算一下时间让loading消失
