### ISSUE TITLE
怎么支持不同速度？传入duration无效？

### ISSUE THREAD

**Issue by XYH1996** [hugeorange/BulletJs#5]
screen.push('<span>123</span>')
                screen.push('<span>阿萨德撒开的速度快</span>')
                screen.push('<span>第三方克里斯多方面是快递费</span>')
                screen.push('<span>手动发生地佛</span>')
                screen.push('<span>第三方乐山大佛马克思的看法</span>')
                screen.push('<span>123</span>')

**Comment by hugeorange** [comment]
> screen.push('123')
> screen.push('阿萨德撒开的速度快')
> screen.push('第三方克里斯多方面是快递费')
> screen.push('手动发生地佛')
> screen.push('第三方乐山大佛马克思的看法')
> screen.push('123')

刚更新了文档，之前md文件的表格语法有错误，导致漏了部分内容，
基本步骤就是将 `speed` 参数设为 `null`， 通过 `duration` 参数控制速度即，弹幕从左到右运行的时间，弹幕越长速度越快

![image](https://user-images.githubusercontent.com/18440746/94768614-7d067700-03e2-11eb-84a5-4e7d43b56f35.png)
